### ISSUE TITLE
How to generate "any" model?

### ISSUE THREAD

**Issue by aclowkey** [pangpanglabs/echoswagger#40]
I have a struct such as:
```
type Entity struct {
    Data interface{}
}
```

I would expect it to be of type 'any'. 
Is it possible to generate this? or alternatively, how to generate "object" type in a struct?

**Comment by elvinchan** [comment]
@aclowkey Since Swagger (or Open API Specification) does not support 'any' type
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types
You must pass an object with the value of concreate type for the interface field. For example, you can use like this:
```
type T struct {
	p    interface{}
	name string
}
type TT struct {
	count int
}
t := T{
	p: TT{
		seq: 1,
	},
	name: "valid",
}
a.AddParamBody(t, t.name, "", true)
```
But the code below is invalid:
```
type T struct {
	p    interface{}
	name string
}
t := T{
	name: "invalid",
}
a.AddParamBody(t, t.name, "", true)
```

**Comment by elvinchan** [comment]
Check these unit tests for more details
https://github.com/pangpanglabs/echoswagger/blob/master/internal_test.go
